version: '3.8'

services:
  recruitment-portal:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=your-secret-key-change-in-production
      - EMAIL_USER=your-email@gmail.com
      - EMAIL_PASS=your-app-password
    volumes:
      - ./uploads:/app/uploads
      - ./recruitment.db:/app/recruitment.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3